---
abstract: 'Parsing args with a richer and more user-friendly API'
author:
  - 'Mytram <mytram2@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Getopt-ArgParse
no_index:
  directory:
    - t
    - inc
requires:
  Getopt::Long: 2.38
  Moo: 1.003
  Test::Exception: 0.31
  perl: 5.008
resources:
  repository: https://github.com/mytram/perl-argparse
version: v1.0.4
